DEFAULT :
    host : 
    port : 
    is_secure : 

fixtures :
    bucket_prefix : s3test-go-

s3main :
    access_key : 
    access_secret : 
    bucket : bucket1
    region : us-east-1
    display_name :
    email : 
    is_secure : 
    SSE : AES256
    kmskeyid : barbican_key_id

s3alt :
    access_key : 
    access_secret : 
    bucket : bucket1
    region : us-east-1
    display_name :
    email : 
    SSE : AES256
    kmskeyid : barbican_key_id
    is_secure : 