DEFAULT :
    host : 
    port : 
    is_secure : 

fixtures :
    bucket_prefix : test-adam

s3main :
    access_key : 0555b35654ad1656d804
    access_secret : h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
    bucket : bucket1
    region : us-east-1
    display_name :
    email : 
    is_secure : false
    SSE : AES256
    kmskeyid : barbican_key_id

s3alt :
    access_key : NOPQRSTUVWXYZABCDEFG
    access_secret : nopqrstuvwxyzabcdefghijklmnabcdefghijklm
    bucket : bucket1
    region : us-east-1
    display_name :
    email : 
    SSE : your SSE
    kmskeyid : barbican_key_id
    is_secure : false